### ISSUE TITLE
How to access the json file with json ?.

### ISSUE THREAD

**Issue by harinanda** [nshntarora/Indian-Cities-JSON#8]
i tries how to access throgh programaticall in node and failed . i am new to json . can you help me

**Comment by nshntarora** [comment]
It's really simple.

First thing you have to do is import the JSON file in your node file and store it in a variable.
`var cities = require('./cities.json');`
Change the location to where your file is located. I'm assuming it's in the same directory as your node script.

The all you have to do is,
`var citiesParsed = JSON.parse(cities);`

What you have right now in the script is a JSON string. What we need is a JSON object array. JSON.parse is used to convert the javascript string array into a JSON object array.

Now is you do `console.log(citiesParsed[0])` It will print the first city (with index 0) object to the console.

Similarly, if you do `console.log(citiesParsed[0].id)` It will print the ID of the city with index 0 and `console.log(citiesParsed[0].name)` will print the name of the city object with index 0

In order to give you a demo I ran the above steps in my browser console. Check out this screenshot.

![citiesjson](https://cloud.githubusercontent.com/assets/8947356/15912143/60681d96-2df0-11e6-8ccf-8429301f59fb.png)

Let me know if you need anything else :smile:
